add basic integration test case.
Yoctol/DS-post-interview-assignment pull request #7
Opened 2018-10-11 10:12 UTC by noobOriented

2018-10-11 10:51 UTC, stegben requested changes
其餘 LGTM

2018-10-11 10:51 UTC, stegben commented on encoder/__init__.py
> +from .encoder import Encoder
少一行

2018-10-11 10:51 UTC, stegben commented on encoder/task.py
> +    def __init__(self, name: str, n_labels: int):
Binary 的話就不用給 `n_labels` 唄，然後 super 的 output_dim 給 1

2018-10-11 10:51 UTC, stegben commented on encoder/task.py
> +        super().__init__(name=name, output_dim=1)
這裡是不是跟 Binary 寫反了？

2018-10-12 03:53 UTC, noobOriented commented on encoder/__init__.py
> +from .encoder import Encoder
我 flake8設不檢查這個檔案，這樣ok?

2018-10-12 03:53 UTC, noobOriented commented on encoder/task.py
> +    def __init__(self, name: str, n_labels: int):
可能multi label

2018-10-12 03:56 UTC, noobOriented commented on encoder/task.py
> +        super().__init__(name=name, output_dim=1)
這個是設定成  一維的discrete class index的label
要自己轉成 onehot (在tf or np)
就是多個multiclass 只會選一

而 Binary是   多個True/ False的感覺

2018-10-12 06:05 UTC, stegben approved these changes

2018-10-12 06:05 UTC, merged